### ISSUE TITLE
Default convention is using an internal tool

### ISSUE THREAD

**Issue by BrentRobert** [phpro/symfony-conventions#10]
The symfony-conventions have been opensourced, however the default configuration still references our internal tool 'kevin'.

https://github.com/phpro/symfony-conventions/blob/8033d1550becd24b98a2d1e1c3755d7e123739ca/grumphp-convention.yml#L7

**Comment by veewee** [comment]
The package is mostly aimed for development at PHPro.
kevin is publicly available.
People can customize this.
